### ISSUE TITLE
Intro, links and Talking math in public conference

### ISSUE THREAD

**Issue by fgbossema** [NLeSC/Scicomm-SIG#15]
Hi all, 

My name is Francien, I'm one of the 2023 Fellows. I've done a masters in Math with a specialisation in Science Communication and Society in Leiden (https://www.universiteitleiden.nl/en/science/science-communication-and-society). I'm currently doing a PhD (last months!) at CWI and Rijksmuseum, on the topic of X-ray Computed Tomography for cultural heritage objects (see https://fgbossema.github.io/). 

During my studies I designed a Math trail through Leiden and later wrote a bookchapter on the design process, together with Charlotte Zwetsloot and Ionica Smeets: https://www.worldscientific.com/doi/10.1142/9789811253072_0005
Please drop me an email (bossema@cwi.nl) if you'd like to have the pdf ;) 

In august there is a conference in New Castle that might be interesting for this group, I will attend! 
https://talkingmathsinpublic.uk/programme/

I'm also enjoying the information collected by Heather Doran and send out in the form of a newsletter each week: https://thescicommer.substack.com/

Looking forward to joining you for future SIG sessions!

**Comment by PabRod** [comment]
Hi @fgbossema. That's amazing!

Coincidentally, I also have a background in [maths and science communication](https://pabrod.github.io/pages/sci-comm-en.html#sci-comm), and since a few days ago I am also working on x-ray tomography. We definitely have to talk! :smiley:.

**Comment by fgbossema** [comment]
Hi @PabRod wow! That sounds like we have a lot to talk about indeed! My next in person meeting at the Escience Center is after I've (hopefully) finished my PhD, and is scheduled for the 28th of September, when I'm also meeting my mentor Valentina live again. Maybe that would be a good moment to have a coffee? (before that I'm trying to make myself focus on finishing the last paper for the phd :P)

**Comment by PabRod** [comment]
I've just sent you a calendar invite.

Good luck with this last step!
