### ISSUE TITLE
Storytelling 

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/Scicomm-SIG#5]
I came across this Ted Talk: 

https://www.ted.com/talks/karen_eber_how_your_brain_responds_to_stories_and_why_they_re_crucial_for_leaders

and as @PabRod keeps reminding us, our brains are made for telling and listening to stories. It would be interesting to discuss in this SIG the power of storytelling for communicating our science.

**Comment by PabRod** [comment]
It has the perfect duration and, most importantly, topic, to make a great SIG session. Thanks!
