### ISSUE TITLE
Physics shows for high-schoolers: my experience with science communication

### ISSUE THREAD

**Issue by sjvrijn** [NLeSC/Scicomm-SIG#6]
During my bachelor and master's studies I've been involved with [Stichting Rino](https://www.stichtingrino.nl). They organize a physics show 'Freezing Physics' based around liquid nitrogen (-196C) at (mostly) Dutch high schools, which I've performed >100 times over a period of ~6.5 years. I've also been involved on the organizational side for a few years.

Some things I could talk about include my experiences in presenting these shows, or what the goals were and how Rino tried to achieve those goals.

**Comment by PabRod** [comment]
Sounds interesting for one of our next sessions. Would you, @sjvrijn, like to talk about this in our March or April session?

**Comment by sjvrijn** [comment]
Sure, both March or April are fine for me

**Comment by PabRod** [comment]
I'll be unable to join the March session (#7). This means that, on the one hand

- it would be great if someone else takes the lead that day

but on the other hand

- it is perhaps not so polite of me to drop this responsibility on you and go away (plus I'd rather not miss your talk!).

Just thinking out loud here. Any opinions?

**Comment by sjvrijn** [comment]
Let's schedule it for April then

**Comment by PabRod** [comment]
I've just realized I cannot join the April session either (in this case, due to holidays). Anyways, I can help organize both.

**Comment by PabRod** [comment]
Thank you for a great talk, @sjvrijn! The discussion it inspired was also awesome!
