### ISSUE TITLE
Chair needed for March 9

### ISSUE THREAD

**Issue by PabRod** [NLeSC/Scicomm-SIG#7]
## Problem

On March 9 I'll be receiving training in another location, so I cannot chair the meeting.

## Solution

Do we have any volunteers to chair the session?

**Comment by Peter9192** [comment]
Guess I'm in the same training

**Comment by PabRod** [comment]
@liekelotte, in order to close today's meeting with specific action points, please let me know if you could change your other appointments and, as a side effect, chair this session.

If you are unable, or I don't hear from you by Tuesday 7th March, I'll just cancel the session.

**Comment by PabRod** [comment]
This session has been cancelled.
